### ISSUE TITLE
Allow true "blank" forks - forks not from mainnet

### ISSUE THREAD

**Issue by kevinhalliday** [recursive-research/neptune#14]
Currently, we impose that forks fork from some provider rpc, or some existing forks. We do not allow creating a true "blank" fork. It's also a bit confusing because the UI says "Blank Fork" but this currently means just forking from mainnet, and not an existing fork. We can fix that confusion separately (I can handle in https://github.com/recursive-research/neptune/pull/13)

I feel like to get use from blank forks, we should also add an easy way to copy the fork id or fork rpc url from the extension itself. 

Separately, since we we suggest contributors add ideas in the "discussions" page, should we move existing issues to discussion? Or just use discussions for new issues.

**Comment by ttarsi** [comment]
Good point. Let's keep issues for bugs / fixes, discussions is for ideas for new features which would include something like this

**Comment by kevinhalliday** [comment]
moving to discussions https://github.com/recursive-research/neptune/discussions/18
