### ISSUE TITLE
Support non-mainnet chains

### ISSUE THREAD

**Issue by ttarsi** [recursive-research/neptune#7]
in both server and extension code, we are not too far away from being able to support multiple chains. we'd only need to:
- expose chainId in fork creation config
- allow input of provider url on fork creation. maintain some mapping of chainId to default provider rpc for convenience
- update active fork when chainId changes

**Comment by kevinhalliday** [comment]
https://github.com/recursive-research/neptune/discussions/19

**Comment by kevinhalliday** [comment]
moving to discussions https://github.com/recursive-research/neptune/discussions/19

**Comment by kevinhalliday** [comment]
moving to discussions https://github.com/recursive-research/neptune/discussions/19
